### ISSUE TITLE
opam install fails if alcotest is installed but ounit isn't

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-flow#13]
The package will attempt to build with tests enabled if alcotest is installed, but it needs both alcotest and OUnit in order to build successfully with tests.  Alcotest no longer requires OUnit itself, so it is possible for the user to have only alcotest installed.

**Comment by samoht** [comment]
hum indeed. Would be nicer to remove OUnit dep completely IMHO, but would be nice the opam metadata first.

**Comment by djs55** [comment]
I think this has been completed -- building without ounit seems to work for me!
